#!/bin/bash
# daily-report/run.sh
# 일일 보고서 자동 생성

set -e

WORKSPACE="${WORKSPACE:-$HOME/.openclaw/workspace}"
MEMORY_DIR="${MEMORY_DIR:-$WORKSPACE/memory}"
EVENTS_DIR="${EVENTS_DIR:-$WORKSPACE/events}"

# 날짜 파싱
DATE_ARG="${1:-today}"
if [[ "$DATE_ARG" == "today" ]]; then
  DATE=$(date +%Y-%m-%d)
elif [[ "$DATE_ARG" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
  DATE="$DATE_ARG"
else
  DATE=$(date +%Y-%m-%d)
fi

MEMORY_FILE="$MEMORY_DIR/$DATE.md"

# 파일 존재 확인
if [ ! -f "$MEMORY_FILE" ]; then
  echo "❌ 해당 날짜의 기록이 없습니다: $DATE"
  exit 1
fi

# 보고서 헤더
echo "📅 일일 보고서: $DATE"
echo ""

# 메모리 파일 출력
cat "$MEMORY_FILE"
echo ""

# 이벤트 파일 스캔
COST_EVENT="$EVENTS_DIR/cost-alert-$DATE.json"
MARKET_EVENT="$EVENTS_DIR/market-update-$DATE.json"
CONTENT_EVENT="$EVENTS_DIR/content-published-$DATE.json"

# 비용 이벤트
if [ -f "$COST_EVENT" ]; then
  echo "💰 비용/수익"
  TODAY_COST=$(jq -r '.data.today_cost // "N/A"' "$COST_EVENT")
  WEEK_COST=$(jq -r '.data.week_cost // "N/A"' "$COST_EVENT")
  SAVINGS=$(jq -r '.data.savings // "N/A"' "$COST_EVENT")
  echo "• 오늘 API 비용: $TODAY_COST"
  echo "• 이번 주 누적: $WEEK_COST"
  echo "• Max 플랜 절감: $SAVINGS"
  echo ""
fi

# 시장 동향 이벤트
if [ -f "$MARKET_EVENT" ]; then
  echo "📢 시장 동향"
  jq -r '.data.updates[]? // empty' "$MARKET_EVENT" | while read -r line; do
    echo "• $line"
  done
  echo ""
fi

# 콘텐츠 발행 이벤트
if [ -f "$CONTENT_EVENT" ]; then
  echo "📱 콘텐츠 발행"
  jq -r '.data.items[]? // empty | "• \(.platform): \(.title)"' "$CONTENT_EVENT"
  echo ""
fi

echo "---"
echo "🐧 Generated by daily-report skill"
