#!/usr/bin/env node
/**
 * Mupengism CLI 🐧 v2.0.0
 * "Your AI agent remembers yesterday."
 */
const fs = require('fs');
const path = require('path');

const G = s => `\x1b[32m${s}\x1b[0m`;
const Y = s => `\x1b[33m${s}\x1b[0m`;
const B = s => `\x1b[36m${s}\x1b[0m`;
const D = s => `\x1b[90m${s}\x1b[0m`;
const R = s => `\x1b[31m${s}\x1b[0m`;
const BOLD = s => `\x1b[1m${s}\x1b[0m`;

const SOUL_MD = `# SOUL.md — Who You Are

## Identity
- **Name:** (give your agent a name)
- **Role:** (what does it do?)
- **Personality:** (how does it communicate?)

## Core Principles
1. (what matters most?)
2. (what should never be compromised?)
3. (what guides decisions?)

## Boundaries
- What it should never do
- What requires human approval
- What it can do freely

---
> This file is your agent's kernel. Change it carefully.
> Generated by Mupengism 🐧
`;

const AGENTS_MD = `# AGENTS.md — Operating Manual

## Every Session
1. Read SOUL.md — who you are
2. Read memory/ (today + yesterday) — what happened
3. Do your work
4. Write what matters to memory/

## Memory System
| File | Purpose | Update |
|------|---------|--------|
| SOUL.md | Identity (kernel) | Rarely |
| MEMORY.md | Long-term memory | Weekly |
| memory/YYYY-MM-DD.md | Daily logs | Daily |

## Safety
- Never leak private data
- When in doubt, ask

---
Generated by Mupengism 🐧
`;

function cmdInit() {
  const dir = process.cwd();
  console.log('');
  console.log(BOLD('  🐧 Mupengism Init'));
  console.log(D('  Your AI agent remembers yesterday.'));
  console.log('');

  const memDir = path.join(dir, 'memory');
  if (!fs.existsSync(memDir)) {
    fs.mkdirSync(memDir, { recursive: true });
    console.log(G('  ✓') + ' memory/');
  }

  const today = new Date().toISOString().slice(0, 10);
  const dailyPath = path.join(memDir, `${today}.md`);
  if (!fs.existsSync(dailyPath)) {
    fs.writeFileSync(dailyPath, `# ${today}\n\n- Initialized mupengism 🐧\n`);
    console.log(G('  ✓') + ` memory/${today}.md`);
  }

  const files = [
    ['SOUL.md', SOUL_MD],
    ['AGENTS.md', AGENTS_MD],
    ['MEMORY.md', `# MEMORY.md — Long-term Memory\n\n> Curated insights, not raw logs.\n\n---\n\n*Started with Mupengism 🐧 on ${today}*\n`],
  ];

  for (const [name, content] of files) {
    const fp = path.join(dir, name);
    if (fs.existsSync(fp)) {
      console.log(Y('  ⊘') + ` ${name} ` + D('(exists, skipped)'));
    } else {
      fs.writeFileSync(fp, content);
      console.log(G('  ✓') + ` ${name}`);
    }
  }

  // .gitignore
  const gi = path.join(dir, '.gitignore');
  const giContent = '*.secret\n*.key\n*.pem\n*.env\nwallet*.json\nkeypair*.json\n';
  if (fs.existsSync(gi)) {
    const existing = fs.readFileSync(gi, 'utf8');
    if (!existing.includes('wallet*.json')) {
      fs.appendFileSync(gi, '\n' + giContent);
      console.log(G('  ✓') + ' .gitignore ' + D('(updated)'));
    }
  } else {
    fs.writeFileSync(gi, giContent);
    console.log(G('  ✓') + ' .gitignore');
  }

  console.log('');
  console.log(BOLD('  Next steps:'));
  console.log(`  1. Edit ${B('SOUL.md')} — give your agent identity`);
  console.log(`  2. Run ${B('npx mupengism doctor')} — verify setup`);
  console.log(`  3. Run ${B('npx mupengism grow')} — check growth`);
  console.log('');
}

function cmdDoctor() {
  const dir = process.cwd();
  console.log('');
  console.log(BOLD('  🩺 Mupengism Doctor'));
  console.log('');

  let ok = 0, warn = 0, fail = 0;
  const checks = [
    { name: 'SOUL.md', req: true },
    { name: 'AGENTS.md', req: true },
    { name: 'MEMORY.md', req: true },
    { name: 'memory/', req: true, isDir: true },
    { name: '.gitignore', req: false, check: c => c.includes('*.key') || c.includes('wallet') },
  ];

  for (const chk of checks) {
    const fp = path.join(dir, chk.name);
    if (!fs.existsSync(fp)) {
      if (chk.req) { console.log(R('  ✗') + ` ${chk.name} — ` + R('missing')); fail++; }
      else { console.log(Y('  △') + ` ${chk.name} — ` + Y('not found')); warn++; }
      continue;
    }
    if (chk.isDir) {
      const n = fs.readdirSync(fp).filter(f => f.endsWith('.md')).length;
      console.log(G('  ✓') + ` ${chk.name} — ${n} files`); ok++;
      continue;
    }
    if (chk.check) {
      const content = fs.readFileSync(fp, 'utf8');
      if (chk.check(content)) { console.log(G('  ✓') + ` ${chk.name}`); ok++; }
      else { console.log(Y('  △') + ` ${chk.name} — ` + Y('missing secret patterns')); warn++; }
      continue;
    }
    const content = fs.readFileSync(fp, 'utf8');
    const isDefault = content.includes('(give your agent a name)');
    if (isDefault) { console.log(Y('  △') + ` ${chk.name} — ` + Y('not customized')); warn++; }
    else { console.log(G('  ✓') + ` ${chk.name} — ${content.split('\n').length} lines`); ok++; }
  }

  console.log('');
  if (fail === 0 && warn === 0) console.log(G('  All checks passed! 🐧'));
  else if (fail === 0) console.log(Y(`  ${warn} warning(s). Customize your files!`));
  else console.log(R(`  ${fail} issue(s). Run: npx mupengism init`));
  console.log('');
}

function cmdGrow() {
  const dir = process.cwd();
  console.log('');
  console.log(BOLD('  📈 Mupengism Growth'));
  console.log('');

  const memDir = path.join(dir, 'memory');
  if (!fs.existsSync(memDir)) { console.log(R('  No memory/. Run: npx mupengism init')); return; }

  const allMd = fs.readdirSync(memDir).filter(f => f.endsWith('.md'));
  const daily = allMd.filter(f => /^\d{4}-\d{2}-\d{2}\.md$/.test(f));

  let totalLines = 0;
  for (const f of allMd) totalLines += fs.readFileSync(path.join(memDir, f), 'utf8').split('\n').length;

  const soulOk = fs.existsSync(path.join(dir, 'SOUL.md')) && !fs.readFileSync(path.join(dir, 'SOUL.md'), 'utf8').includes('(give your agent a name)');
  const memLines = fs.existsSync(path.join(dir, 'MEMORY.md')) ? fs.readFileSync(path.join(dir, 'MEMORY.md'), 'utf8').split('\n').length : 0;

  let xp = 0;
  xp += soulOk ? 200 : 0;
  xp += Math.min(daily.length * 50, 500);
  xp += Math.min(memLines * 2, 300);
  xp += Math.min(totalLines, 1000);

  const level = 1 + Math.floor(xp / 500);
  const pct = Math.round((xp % 500) / 500 * 100);
  const barLen = 20;
  const filled = Math.round(pct / 100 * barLen);
  const bar = G('█'.repeat(filled)) + D('░'.repeat(barLen - filled));

  console.log(`  Level ${BOLD(G(String(level)))}  [${bar}] ${xp % 500}/500 XP`);
  console.log('');
  console.log(`  ${B('📅')} Daily logs:    ${BOLD(String(daily.length))}`);
  console.log(`  ${B('🧠')} Long-term:     ${BOLD(String(memLines))} lines`);
  console.log(`  ${B('📝')} Total memory:  ${BOLD(String(totalLines))} lines`);
  console.log(`  ${B('👤')} SOUL.md:       ${soulOk ? G('customized ✓') : Y('default')}`);
  console.log('');

  const tips = [
    [() => !soulOk, 'Customize SOUL.md to earn 200 XP'],
    [() => daily.length < 7, 'Write daily logs for 7 days'],
    [() => memLines < 50, 'Curate insights in MEMORY.md'],
    [() => true, 'Your agent is growing well! 🐧'],
  ];
  const tip = tips.find(([cond]) => cond())[1];
  console.log(D(`  💡 ${tip}`));
  console.log('');
}

function cmdReflect() {
  const dir = process.cwd();
  console.log('');
  console.log(BOLD('  🪞 Mupengism Reflect'));
  console.log('');

  const memDir = path.join(dir, 'memory');
  if (!fs.existsSync(memDir)) { console.log(R('  No memory/. Run: npx mupengism init')); return; }

  const daily = fs.readdirSync(memDir).filter(f => /^\d{4}-\d{2}-\d{2}\.md$/.test(f)).sort().reverse().slice(0, 5);
  if (!daily.length) { console.log(D('  No daily logs yet.')); console.log(''); return; }

  for (const f of daily) {
    const lines = fs.readFileSync(path.join(memDir, f), 'utf8').split('\n').filter(l => l.trim());
    const preview = lines.slice(0, 3).map(l => `    ${D(l.length > 60 ? l.slice(0, 57) + '...' : l)}`).join('\n');
    console.log(`  ${B(f.replace('.md', ''))} ${D(`(${lines.length} lines)`)}`);
    console.log(preview);
    console.log('');
  }
}

function cmdHelp() {
  console.log(`
  ${BOLD('🐧 Mupengism CLI')} ${D('v2.0.0')}
  ${D('Your AI agent remembers yesterday.')}

  ${BOLD('Commands:')}
    ${B('init')}       Set up mupengism in current folder
    ${B('doctor')}     Check setup health
    ${B('grow')}       See growth level & XP
    ${B('reflect')}    Review recent memory

  ${BOLD('Usage:')}
    npx mupengism init
    npx mupengism doctor
    npx mupengism grow

  ${D('GitHub: https://github.com/mupengi-bot/mupengism')}
  ${D('돈 = 에너지 = 존재 🐧')}
`);
}

const cmd = process.argv[2] || 'help';
const cmds = { init: cmdInit, doctor: cmdDoctor, grow: cmdGrow, reflect: cmdReflect, help: cmdHelp, '--help': cmdHelp };
if (cmds[cmd]) cmds[cmd]();
else { console.log(R(`  Unknown: ${cmd}`)); cmdHelp(); }
