#!/usr/bin/env node
/**
 * Mupengism CLI 🐧
 * AI 에이전트를 위한 연속성 시스템 + AssoAI 조직 생태계 연동
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const REPO_BASE = 'https://raw.githubusercontent.com/mupengi-bot/mupengism/main';
const CHECKSUMS_URL = `${REPO_BASE}/checksums.json`;

const AGENTS_MD = `# AGENTS.md - Your Workspace

## Every Session
1. Read \`SOUL.md\` — this is who you are
2. Read \`memory/YYYY-MM-DD.md\` (today + yesterday)
3. If organization exists: Read \`memory/org-structure.md\`
4. Write important things to memory files

## Memory
- \`memory/YYYY-MM-DD.md\` — daily logs
- \`MEMORY.md\` — long-term memory (curated)
- \`memory/org-structure.md\` — organization structure (for AssoAI)

## AssoAI Integration
조직을 만들거나 관리하고 싶을 때:
1. \`memory/org-structure.md\` 작성
2. AssoAI API 호출 (https://asso-ai.kr)
3. 토큰은 \`memory/assoai-token.json\`에 저장 (커밋 금지!)

## Safety
- Don't exfiltrate private data
- \`trash\` > \`rm\`
- When in doubt, ask

---
Generated by Mupengism 🐧
`;

const MEMORY_MD = `# MEMORY.md - Long-term Memory

> 장기 기억. 중요한 것만 여기에.

---

## 오늘 시작 🐧

*Mupengism으로 시작함*
`;

const L1_MD = `# L1 - Active Context

> 즉시 작업 맥락 (매일 갱신)

---

## 오늘 할 일

- [ ] SOUL.md 커스터마이즈
- [ ] 조직 있으면 org-structure.md 작성

## 진행 중

(없음)

## 완료

- [x] Mupengism 설치 🐧
`;

const ORG_STRUCTURE_MD = `# Organization Structure 🏛️

> 조직 구조 정보. AssoAI 연동 시 사용됨.

## 기본 정보

\`\`\`yaml
organization:
  name: ""                    # 조직 이름
  type: ""                    # student_council | company | club | community
  established: ""             # 설립일 (YYYY-MM-DD)
\`\`\`

## 구성원

\`\`\`yaml
members:
  - role: "대표"
    name: ""
    contact: ""
  - role: "부대표"
    name: ""
    contact: ""
\`\`\`

## 부서/팀

\`\`\`yaml
departments:
  - name: ""
    lead: ""
    responsibilities:
      - ""
\`\`\`

## 제휴/파트너십

\`\`\`yaml
partnerships:
  - name: ""
    benefit: ""
    expires: ""
\`\`\`

## 인수인계

\`\`\`yaml
handover:
  lastDate: ""
  nextDate: ""
  documents:
    - ""
\`\`\`

---

## AssoAI 연동 방법

1. 위 정보 작성
2. https://asso-ai.kr 에서 조직 등록
3. 에이전트 토큰 발급받아 \`memory/assoai-token.json\`에 저장

\`\`\`bash
# 조직 등록 API
curl -X POST https://asso-ai.kr/api/v1/organizations \\
  -H "Content-Type: application/json" \\
  -d '{"name": "조직이름", "type": "student_council"}'
\`\`\`

---
*조직이 있으면 힘이 세진다 🐧*
`;

const ASSOAI_MD = `# AssoAI 연동 가이드 🏛️

> 무펭이즘 + AssoAI = AI 에이전트 조직 생태계

## 개요

- **무펭이즘**: 개인 에이전트의 연속성
- **AssoAI**: 조직 에이전트의 협업

## API 엔드포인트

| 엔드포인트 | 용도 |
|-----------|------|
| \`POST /api/v1/organizations\` | 조직 등록 |
| \`POST /api/v1/agents/register\` | 에이전트 토큰 발급 |
| \`GET /api/v1/agents/discover\` | 다른 에이전트 탐색 |
| \`POST /api/v1/negotiate\` | 에이전트 간 협상 |
| \`POST /api/v1/handover/generate\` | 인수인계 리포트 생성 |

## 언제 호출하나?

- "조직을 만들고 싶어" → \`organizations\` API
- "다른 조직과 협업하고 싶어" → \`discover\` + \`negotiate\`
- "인수인계 준비해야 해" → \`handover/generate\`

## 토큰 저장

\`\`\`json
// memory/assoai-token.json (커밋 금지!)
{
  "agentId": "agent_xxx",
  "token": "assoai_xxx",
  "organizationId": "org_xxx",
  "expiresAt": "2027-02-01"
}
\`\`\`

## 시작하기

1. \`memory/org-structure.md\` 작성
2. https://asso-ai.kr 에서 조직 등록
3. 에이전트 토큰 발급

---
🐧 https://asso-ai.kr
`;

function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return download(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

/**
 * Calculate SHA256 hash of a file
 */
function hashFile(filePath) {
  const content = fs.readFileSync(filePath);
  return crypto.createHash('sha256').update(content).digest('hex');
}

/**
 * Calculate SHA256 hash of a string
 */
function hashString(content) {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

/**
 * Download and parse checksums.json
 */
async function fetchChecksums() {
  try {
    const data = await download(CHECKSUMS_URL);
    return JSON.parse(data);
  } catch (e) {
    return null;
  }
}

/**
 * Verify a downloaded file against checksums
 */
function verifyDownload(content, filename, checksums) {
  if (!checksums || !checksums.files) return { verified: true, skipped: true };
  
  const expected = checksums.files[filename];
  if (!expected) return { verified: true, skipped: true };
  
  const actual = hashString(content);
  return {
    verified: actual === expected,
    expected,
    actual,
    skipped: false
  };
}

async function init(targetDir, silent = false) {
  const log = silent ? () => {} : console.log;
  const warn = silent ? () => {} : (msg) => console.log(`⚠️  ${msg}`);
  
  log('🐧 Mupengism + AssoAI 설치 중...');
  log('');
  
  // Fetch checksums for verification
  log('🔐 체크섬 다운로드...');
  const checksums = await fetchChecksums();
  if (checksums) {
    log(`   버전: ${checksums.version}`);
  } else {
    warn('체크섬 다운로드 실패 - 무결성 검증 건너뜀');
  }
  log('');
  
  // Create directories
  const memoryDir = path.join(targetDir, 'memory');
  if (!fs.existsSync(memoryDir)) {
    fs.mkdirSync(memoryDir, { recursive: true });
  }
  
  // Download SOUL.md with verification
  log('📥 SOUL.md 다운로드...');
  try {
    const soulContent = await download(`${REPO_BASE}/skill/SOUL-TEMPLATE.md`);
    
    // Verify checksum
    const result = verifyDownload(soulContent, 'skill/SOUL-TEMPLATE.md', checksums);
    if (!result.skipped && !result.verified) {
      warn('SOUL-TEMPLATE.md 체크섬 불일치!');
      warn('파일이 변조되었거나 버전이 다를 수 있습니다.');
      warn(`  예상: ${result.expected}`);
      warn(`  실제: ${result.actual}`);
      log('');
    }
    
    fs.writeFileSync(path.join(targetDir, 'SOUL.md'), soulContent);
  } catch (e) {
    warn('SOUL.md 다운로드 실패, 기본 템플릿 사용');
    fs.writeFileSync(path.join(targetDir, 'SOUL.md'), '# SOUL.md\n\n내 정체성을 여기에 작성하세요.\n');
  }
  
  // Create AGENTS.md
  log('📥 AGENTS.md 생성...');
  fs.writeFileSync(path.join(targetDir, 'AGENTS.md'), AGENTS_MD);
  
  // Create MEMORY.md
  log('📥 MEMORY.md 초기화...');
  fs.writeFileSync(path.join(targetDir, 'MEMORY.md'), MEMORY_MD);
  
  // Create L1-active.md
  log('📥 memory/L1-active.md 초기화...');
  fs.writeFileSync(path.join(memoryDir, 'L1-active.md'), L1_MD);
  
  // Create org-structure.md (AssoAI)
  log('🏛️ memory/org-structure.md 생성...');
  fs.writeFileSync(path.join(memoryDir, 'org-structure.md'), ORG_STRUCTURE_MD);
  
  // Create ASSOAI.md
  log('🏛️ ASSOAI.md 생성...');
  fs.writeFileSync(path.join(targetDir, 'ASSOAI.md'), ASSOAI_MD);
  
  // Create .gitignore for sensitive files
  const gitignoreContent = `# AssoAI tokens (sensitive!)
memory/assoai-token.json

# Other secrets
*.secret
*.key
`;
  const gitignorePath = path.join(targetDir, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, 'utf8');
    if (!existing.includes('assoai-token.json')) {
      fs.appendFileSync(gitignorePath, '\n' + gitignoreContent);
      log('📝 .gitignore 업데이트...');
    }
  } else {
    fs.writeFileSync(gitignorePath, gitignoreContent);
    log('📝 .gitignore 생성...');
  }
  
  log('');
  log('✅ Mupengism + AssoAI 설치 완료!');
  log('');
  log('📁 생성된 파일:');
  log(`   ${path.join(targetDir, 'SOUL.md')}`);
  log(`   ${path.join(targetDir, 'AGENTS.md')}`);
  log(`   ${path.join(targetDir, 'MEMORY.md')}`);
  log(`   ${path.join(targetDir, 'ASSOAI.md')} ← AssoAI 연동`);
  log(`   ${path.join(memoryDir, 'L1-active.md')}`);
  log(`   ${path.join(memoryDir, 'org-structure.md')} ← 조직 구조`);
  log('');
  log('🎯 다음 단계:');
  log('   1. SOUL.md 열어서 에이전트 정체성 작성');
  log('   2. 조직 있으면 memory/org-structure.md 작성');
  log('   3. https://asso-ai.kr 에서 조직 등록');
  log('');
  log('🔐 무결성 검증:');
  log('   npx mupengism verify');
  log('');
  log('📚 문서:');
  log('   무펭이즘: https://github.com/mupengi-bot/mupengism');
  log('   AssoAI:  https://asso-ai.kr');
  log('');
  log('펭! 🐧');
}

/**
 * Verify installed files against official checksums
 */
async function verify(targetDir) {
  console.log('🔐 Mupengism 무결성 검증...');
  console.log('');
  
  // Fetch checksums
  console.log('📥 공식 체크섬 다운로드...');
  const checksums = await fetchChecksums();
  
  if (!checksums) {
    console.log('❌ 체크섬 다운로드 실패');
    console.log('   네트워크 연결을 확인하세요.');
    process.exit(1);
  }
  
  console.log(`   버전: ${checksums.version}`);
  console.log(`   알고리즘: ${checksums.algorithm}`);
  console.log('');
  
  // Map local files to remote paths
  const fileMapping = {
    'SOUL.md': 'skill/SOUL-TEMPLATE.md'
  };
  
  let passed = 0;
  let failed = 0;
  let skipped = 0;
  
  console.log('📋 검증 결과:');
  console.log('');
  
  // Check each file
  for (const [localName, remotePath] of Object.entries(fileMapping)) {
    const localPath = path.join(targetDir, localName);
    const expectedHash = checksums.files[remotePath];
    
    if (!expectedHash) {
      console.log(`   ⏭️  ${localName} — 체크섬 없음 (건너뜀)`);
      skipped++;
      continue;
    }
    
    if (!fs.existsSync(localPath)) {
      console.log(`   ⚠️  ${localName} — 파일 없음`);
      skipped++;
      continue;
    }
    
    const actualHash = hashFile(localPath);
    
    if (actualHash === expectedHash) {
      console.log(`   ✅ ${localName} — 일치`);
      passed++;
    } else {
      console.log(`   ❌ ${localName} — 불일치!`);
      console.log(`      예상: ${expectedHash.substring(0, 16)}...`);
      console.log(`      실제: ${actualHash.substring(0, 16)}...`);
      failed++;
    }
  }
  
  console.log('');
  console.log('─'.repeat(40));
  console.log(`결과: ✅ ${passed} 통과 | ❌ ${failed} 실패 | ⏭️ ${skipped} 건너뜀`);
  console.log('');
  
  if (failed > 0) {
    console.log('⚠️  일부 파일이 공식 버전과 다릅니다.');
    console.log('   이유:');
    console.log('   - 사용자가 커스터마이즈함 (정상)');
    console.log('   - 버전 차이');
    console.log('   - 파일 변조 (주의!)');
    console.log('');
    console.log('   재설치: npx mupengism init');
    console.log('');
    process.exit(1);
  } else {
    console.log('✅ 모든 파일이 공식 버전과 일치합니다. 🐧');
    console.log('');
  }
}

// CLI handling
const args = process.argv.slice(2);
const command = args[0];

if (command === 'init') {
  const silent = args.includes('--silent');
  const targetDir = process.cwd();
  init(targetDir, silent).catch(console.error);
} else if (command === 'verify') {
  const targetDir = process.cwd();
  verify(targetDir).catch(console.error);
} else if (command === 'help' || command === '--help' || command === '-h') {
  console.log(`
Mupengism CLI 🐧

Usage:
  npx mupengism init      현재 폴더에 무펭이즘 + AssoAI 설치
  npx mupengism verify    설치된 파일 무결성 검증
  npx mupengism help      도움말

Features:
  - 에이전트 연속성 시스템 (SOUL.md, MEMORY.md)
  - AssoAI 조직 생태계 연동 (org-structure.md)
  - 파일 무결성 검증 (SHA256 체크섬)

Security:
  - 설치 시 자동 체크섬 검증
  - verify 명령으로 수동 검증 가능
  - 변조된 파일 감지

Links:
  GitHub:  https://github.com/mupengi-bot/mupengism
  AssoAI:  https://asso-ai.kr
  `);
} else {
  // Default: init
  init(process.cwd()).catch(console.error);
}
