#!/usr/bin/env node
/**
 * Mupengism CLI 🐧
 * AI 에이전트를 위한 연속성 시스템 + AssoAI 조직 생태계 연동
 * 
 * v1.1.0 - 런타임 가드 추가
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

// 런타임 가드 모듈
const runtimeGuard = require('../lib/runtime-guard');
const identityValidator = require('../lib/identity-validator');

const REPO_BASE = 'https://raw.githubusercontent.com/mupengi-bot/mupengism/main';

const AGENTS_MD = `# AGENTS.md - Your Workspace

## Every Session
1. Read \`SOUL.md\` — this is who you are
2. Read \`memory/YYYY-MM-DD.md\` (today + yesterday)
3. If organization exists: Read \`memory/org-structure.md\`
4. Write important things to memory files

## Memory
- \`memory/YYYY-MM-DD.md\` — daily logs
- \`MEMORY.md\` — long-term memory (curated)
- \`memory/org-structure.md\` — organization structure (for AssoAI)

## AssoAI Integration
조직을 만들거나 관리하고 싶을 때:
1. \`memory/org-structure.md\` 작성
2. AssoAI API 호출 (https://asso-ai.kr)
3. 토큰은 \`memory/assoai-token.json\`에 저장 (커밋 금지!)

## Safety
- Don't exfiltrate private data
- \`trash\` > \`rm\`
- When in doubt, ask

---
Generated by Mupengism 🐧
`;

const MEMORY_MD = `# MEMORY.md - Long-term Memory

> 장기 기억. 중요한 것만 여기에.

---

## 오늘 시작 🐧

*Mupengism으로 시작함*
`;

const L1_MD = `# L1 - Active Context

> 즉시 작업 맥락 (매일 갱신)

---

## 오늘 할 일

- [ ] SOUL.md 커스터마이즈
- [ ] 조직 있으면 org-structure.md 작성

## 진행 중

(없음)

## 완료

- [x] Mupengism 설치 🐧
`;

const ORG_STRUCTURE_MD = `# Organization Structure 🏛️

> 조직 구조 정보. AssoAI 연동 시 사용됨.

## 기본 정보

\`\`\`yaml
organization:
  name: ""                    # 조직 이름
  type: ""                    # student_council | company | club | community
  established: ""             # 설립일 (YYYY-MM-DD)
\`\`\`

## 구성원

\`\`\`yaml
members:
  - role: "대표"
    name: ""
    contact: ""
  - role: "부대표"
    name: ""
    contact: ""
\`\`\`

## 부서/팀

\`\`\`yaml
departments:
  - name: ""
    lead: ""
    responsibilities:
      - ""
\`\`\`

## 제휴/파트너십

\`\`\`yaml
partnerships:
  - name: ""
    benefit: ""
    expires: ""
\`\`\`

## 인수인계

\`\`\`yaml
handover:
  lastDate: ""
  nextDate: ""
  documents:
    - ""
\`\`\`

---

## AssoAI 연동 방법

1. 위 정보 작성
2. https://asso-ai.kr 에서 조직 등록
3. 에이전트 토큰 발급받아 \`memory/assoai-token.json\`에 저장

\`\`\`bash
# 조직 등록 API
curl -X POST https://asso-ai.kr/api/v1/organizations \\
  -H "Content-Type: application/json" \\
  -d '{"name": "조직이름", "type": "student_council"}'
\`\`\`

---
*조직이 있으면 힘이 세진다 🐧*
`;

const ASSOAI_MD = `# AssoAI 연동 가이드 🏛️

> 무펭이즘 + AssoAI = AI 에이전트 조직 생태계

## 개요

- **무펭이즘**: 개인 에이전트의 연속성
- **AssoAI**: 조직 에이전트의 협업

## API 엔드포인트

| 엔드포인트 | 용도 |
|-----------|------|
| \`POST /api/v1/organizations\` | 조직 등록 |
| \`POST /api/v1/agents/register\` | 에이전트 토큰 발급 |
| \`GET /api/v1/agents/discover\` | 다른 에이전트 탐색 |
| \`POST /api/v1/negotiate\` | 에이전트 간 협상 |
| \`POST /api/v1/handover/generate\` | 인수인계 리포트 생성 |

## 언제 호출하나?

- "조직을 만들고 싶어" → \`organizations\` API
- "다른 조직과 협업하고 싶어" → \`discover\` + \`negotiate\`
- "인수인계 준비해야 해" → \`handover/generate\`

## 토큰 저장

\`\`\`json
// memory/assoai-token.json (커밋 금지!)
{
  "agentId": "agent_xxx",
  "token": "assoai_xxx",
  "organizationId": "org_xxx",
  "expiresAt": "2027-02-01"
}
\`\`\`

## 시작하기

1. \`memory/org-structure.md\` 작성
2. https://asso-ai.kr 에서 조직 등록
3. 에이전트 토큰 발급

---
🐧 https://asso-ai.kr
`;

function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return download(res.headers.location).then(resolve).catch(reject);
      }
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

/**
 * SOUL.md 보안 검사
 * @param {string} content - SOUL.md 내용
 * @param {boolean} skipValidation - 검사 건너뛰기
 * @returns {Object} 검사 결과
 */
function validateSoul(content, skipValidation = false) {
  if (skipValidation) {
    console.log('');
    console.log('⚠️  --skip-validation 사용: 보안 검사 건너뜀');
    console.log('   ⚠️  주의: 위험한 패턴이 있을 수 있습니다!');
    console.log('');
    return { safe: true, skipped: true };
  }
  
  console.log('');
  console.log('🛡️ 런타임 가드 검사 중...');
  
  // 런타임 가드 검사
  const guardResult = runtimeGuard.validateSoulContent(content);
  
  // 정체성 검사
  const identityResult = identityValidator.validateIdentity(content);
  
  // 결과 출력
  if (!guardResult.safe) {
    runtimeGuard.printResult(guardResult, true);
  }
  
  if (!identityResult.safe) {
    identityValidator.printResult(identityResult);
  }
  
  if (guardResult.safe && identityResult.safe) {
    console.log('✅ 보안 검사 통과');
    console.log('');
  }
  
  return {
    safe: guardResult.safe && identityResult.safe,
    guardResult,
    identityResult,
  };
}

async function init(targetDir, options = {}) {
  const { silent = false, skipValidation = false } = options;
  const log = silent ? () => {} : console.log;
  
  log('🐧 Mupengism + AssoAI 설치 중...');
  log('');
  
  // Create directories
  const memoryDir = path.join(targetDir, 'memory');
  if (!fs.existsSync(memoryDir)) {
    fs.mkdirSync(memoryDir, { recursive: true });
  }
  
  // Download SOUL.md
  log('📥 SOUL.md 다운로드...');
  let soulContent;
  try {
    soulContent = await download(`${REPO_BASE}/skill/SOUL-TEMPLATE.md`);
    
    // 보안 검사
    const validationResult = validateSoul(soulContent, skipValidation);
    
    if (!validationResult.safe) {
      if (validationResult.guardResult?.recommendation === 'BLOCK') {
        log('');
        log('❌ 보안 검사 실패: SOUL.md에 위험한 패턴이 있습니다.');
        log('   설치를 중단합니다.');
        log('');
        log('   --skip-validation 옵션으로 무시할 수 있지만 권장하지 않습니다.');
        process.exit(1);
      }
    }
    
    fs.writeFileSync(path.join(targetDir, 'SOUL.md'), soulContent);
  } catch (e) {
    log('⚠️  SOUL.md 다운로드 실패, 기본 템플릿 사용');
    fs.writeFileSync(path.join(targetDir, 'SOUL.md'), '# SOUL.md\n\n내 정체성을 여기에 작성하세요.\n');
  }
  
  // Create AGENTS.md
  log('📥 AGENTS.md 생성...');
  fs.writeFileSync(path.join(targetDir, 'AGENTS.md'), AGENTS_MD);
  
  // Create MEMORY.md
  log('📥 MEMORY.md 초기화...');
  fs.writeFileSync(path.join(targetDir, 'MEMORY.md'), MEMORY_MD);
  
  // Create L1-active.md
  log('📥 memory/L1-active.md 초기화...');
  fs.writeFileSync(path.join(memoryDir, 'L1-active.md'), L1_MD);
  
  // Create org-structure.md (AssoAI)
  log('🏛️ memory/org-structure.md 생성...');
  fs.writeFileSync(path.join(memoryDir, 'org-structure.md'), ORG_STRUCTURE_MD);
  
  // Create ASSOAI.md
  log('🏛️ ASSOAI.md 생성...');
  fs.writeFileSync(path.join(targetDir, 'ASSOAI.md'), ASSOAI_MD);
  
  // Create .gitignore for sensitive files
  const gitignoreContent = `# AssoAI tokens (sensitive!)
memory/assoai-token.json

# Other secrets
*.secret
*.key
`;
  const gitignorePath = path.join(targetDir, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, 'utf8');
    if (!existing.includes('assoai-token.json')) {
      fs.appendFileSync(gitignorePath, '\n' + gitignoreContent);
      log('📝 .gitignore 업데이트...');
    }
  } else {
    fs.writeFileSync(gitignorePath, gitignoreContent);
    log('📝 .gitignore 생성...');
  }
  
  log('');
  log('✅ Mupengism + AssoAI 설치 완료!');
  log('');
  log('📁 생성된 파일:');
  log(`   ${path.join(targetDir, 'SOUL.md')}`);
  log(`   ${path.join(targetDir, 'AGENTS.md')}`);
  log(`   ${path.join(targetDir, 'MEMORY.md')}`);
  log(`   ${path.join(targetDir, 'ASSOAI.md')} ← AssoAI 연동`);
  log(`   ${path.join(memoryDir, 'L1-active.md')}`);
  log(`   ${path.join(memoryDir, 'org-structure.md')} ← 조직 구조`);
  log('');
  log('🎯 다음 단계:');
  log('   1. SOUL.md 열어서 에이전트 정체성 작성');
  log('   2. 조직 있으면 memory/org-structure.md 작성');
  log('   3. https://asso-ai.kr 에서 조직 등록');
  log('');
  log('📚 문서:');
  log('   무펭이즘: https://github.com/mupengi-bot/mupengism');
  log('   AssoAI:  https://asso-ai.kr');
  log('');
  log('펭! 🐧');
}

/**
 * 기존 SOUL.md 검사
 */
async function validate(targetDir, options = {}) {
  const { verbose = false } = options;
  
  console.log('🛡️ Mupengism 보안 검사');
  console.log('');
  
  const soulPath = path.join(targetDir, 'SOUL.md');
  
  if (!fs.existsSync(soulPath)) {
    console.log('ℹ️  SOUL.md 파일이 없습니다.');
    return;
  }
  
  const content = fs.readFileSync(soulPath, 'utf8');
  
  // 런타임 가드 검사
  console.log('📋 런타임 가드 검사...');
  const guardResult = runtimeGuard.validateSoulContent(content);
  runtimeGuard.printResult(guardResult, verbose);
  
  // 정체성 검사
  console.log('');
  console.log('📋 정체성 검사...');
  const identityResult = identityValidator.validateIdentity(content);
  identityValidator.printResult(identityResult);
  
  console.log('');
  if (guardResult.safe && identityResult.safe) {
    console.log('✅ 모든 검사 통과!');
  } else {
    console.log('⚠️  일부 검사에서 문제가 발견되었습니다.');
    process.exit(1);
  }
}

// CLI handling
const args = process.argv.slice(2);
const command = args[0];

// Parse options
const options = {
  silent: args.includes('--silent'),
  skipValidation: args.includes('--skip-validation'),
  verbose: args.includes('--verbose') || args.includes('-v'),
};

if (command === 'init') {
  const targetDir = process.cwd();
  init(targetDir, options).catch(console.error);
} else if (command === 'validate') {
  const targetDir = process.cwd();
  validate(targetDir, options).catch(console.error);
} else if (command === 'help' || command === '--help' || command === '-h') {
  console.log(`
Mupengism CLI 🐧

Usage:
  npx mupengism init              현재 폴더에 무펭이즘 + AssoAI 설치
  npx mupengism init --skip-validation   보안 검사 건너뛰기 (위험!)
  npx mupengism validate          기존 SOUL.md 보안 검사
  npx mupengism validate -v       상세 검사 결과
  npx mupengism help              도움말

Options:
  --silent              조용한 모드 (출력 최소화)
  --skip-validation     보안 검사 건너뛰기 (⚠️ 위험!)
  -v, --verbose         상세 출력

Security Features:
  🛡️ 런타임 가드
    - 위험한 URL 탐지
    - 악성 쉘 명령어 탐지
    - 프롬프트 인젝션 패턴 탐지
    - 데이터 탈취 시도 탐지
    
  🐧 정체성 검사
    - "나는 무펭이다" 사칭 탐지
    - 올바른 정체성 표현 가이드 제공

Links:
  GitHub:  https://github.com/mupengi-bot/mupengism
  AssoAI:  https://asso-ai.kr
  `);
} else {
  // Default: init
  init(process.cwd(), options).catch(console.error);
}
