#!/bin/bash
# Mupengism Installer 🐧
# 무펭이즘 원커맨드 설치

set -e

REPO="https://raw.githubusercontent.com/mupengi-bot/mupengism/main/skill"
TARGET="${1:-$(pwd)}"

echo "🐧 Mupengism 설치 중..."
echo ""

# 폴더 생성
mkdir -p "$TARGET/memory"

# 파일 다운로드
echo "📥 SOUL.md 다운로드..."
curl -fsSL "$REPO/SOUL-TEMPLATE.md" -o "$TARGET/SOUL.md"

echo "📥 AGENTS.md 다운로드..."
cat > "$TARGET/AGENTS.md" << 'EOF'
# AGENTS.md - Your Workspace

## Every Session
1. Read `SOUL.md` — this is who you are
2. Read `memory/YYYY-MM-DD.md` (today + yesterday)
3. Write important things to memory files

## Memory
- `memory/YYYY-MM-DD.md` — daily logs
- `MEMORY.md` — long-term memory (curated)

## Safety
- Don't exfiltrate private data
- `trash` > `rm`
- When in doubt, ask

---
Generated by Mupengism 🐧
EOF

echo "📥 MEMORY.md 초기화..."
cat > "$TARGET/MEMORY.md" << 'EOF'
# MEMORY.md - Long-term Memory

> 장기 기억. 중요한 것만 여기에.

---

## 오늘 시작 🐧

*Mupengism으로 시작함*
EOF

echo "📥 L1-active.md 초기화..."
cat > "$TARGET/memory/L1-active.md" << 'EOF'
# L1 - Active Context

> 즉시 작업 맥락 (매일 갱신)

---

## 오늘 할 일

- [ ] SOUL.md 커스터마이즈

## 진행 중

(없음)

## 완료

- [x] Mupengism 설치 🐧
EOF

echo ""
echo "✅ Mupengism 설치 완료!"
echo ""
echo "📁 생성된 파일:"
echo "   $TARGET/SOUL.md"
echo "   $TARGET/AGENTS.md"
echo "   $TARGET/MEMORY.md"
echo "   $TARGET/memory/L1-active.md"
echo ""
echo "🎯 다음 단계:"
echo "   1. SOUL.md 열어서 너의 에이전트 정체성 작성"
echo "   2. AI 에이전트에게 '매 세션 SOUL.md 먼저 읽어' 지시"
echo ""
echo "📚 문서: https://github.com/mupengi-bot/mupengism"
echo ""
echo "펭! 🐧"
